import CashierTemplate from "@/components/managerTemplate"
import MenuList from "../menuList"

export const metadata = {
    title: 'MyStory',
    description: 'Generated by create next app',
}

type PropsLayout = {
    children: React.ReactNode
}
const RootLayout = ({ children }: PropsLayout) => {
    return (
        <CashierTemplate title="MyStory" id="MyStory" menuList={MenuList}>
            {children}
        </CashierTemplate>
    )
}
export default RootLayout